"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 3.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import pymysql
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x09^n08_t&me=0ck(ebp9vlva^!vfa=g8_$4gienx%r-esvs@l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# production
# ALLOWED_HOSTS = ['0.0.0.0']

# development
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'requests',
    'corsheaders',
    'rest_framework',
    #'fuk.apps.FukConfig',
    # 'fuk',
    'eprint.apps.EprintConfig',
    'fuk_aktivnost.apps.FukAktivnostConfig',
    'fuk_gfuk.apps.FukGfukConfig',
    'fuk_help.apps.FukHelpConfig',
    'fuk_oblast.apps.FukOblastConfig',
    'fuk_organizacija.apps.FukOrganizacijaConfig',
    'fuk_orgjed.apps.FukOrgjedConfig',
    'fuk_potpis.apps.FukPotpisConfig',
    'fuk_procedura.apps.FukProceduraConfig',
    'fuk_proces.apps.FukProcesConfig',
    'fuk_proces_veza.apps.FukProcesVezaConfig',
    'fuk_rizik.apps.FukRizikConfig',
    'fuk_riziks.apps.FukRiziksConfig',
    'fuk_nepravilnosti.apps.FukNepravilnostiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

pymysql.install_as_MySQLdb()

# production
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'electususers',
#         'USER': os.environ.get('MYSQL_ROOT_USER'),
#         'PASSWORD': os.environ.get('MYSQL_ROOT_PASSWORD'),
#         'HOST': 'database',
#         'PORT': 3306,
#     },
#     'fuk_db': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'fuktabele',
#         'USER': os.environ.get('MYSQL_ROOT_USER'),
#         'PASSWORD': os.environ.get('MYSQL_ROOT_PASSWORD'),
#         'HOST': 'database',
#         'PORT': 3306,
#     }
# }
# development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR, 'electus.cnf'),
        }
    },
    'fuk_db': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR, 'fuk.cnf'),
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Belgrade'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_URL = '/django_static/'
STATIC_ROOT = BASE_DIR / 'django_static'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASE_ROUTERS = [
    'routers.db_routers.AuthRouter',
    'routers.db_routers.FukRouter', 
]

# Rest
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ]
}

CORS_ORIGIN_ALLOW_ALL = True
# define which origins are allowed
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000"
# ]

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 10 * 60 * 60 # 10 hours

