version: '3'
services:
  database:
    build:
      context: .
      dockerfile: ./mariadb/Dockerfile
    volumes:
      - ./data.db:/var/lib/mysql/data
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
  backend:
    build:
      context: ./backend
    command: gunicorn base.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=electus
      - MYSQL_PASSWORD=electus123
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=toor
      # - MYSQL_DATABASE_HOST=127.0.0.1
      - MYSQL_DATABASE_PORT=3306
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_build:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend
    depends_on:
      - database
      - backend
      - frontend
volumes:
  frontend_build:
