# Generated by Django 3.2.10 on 2023-03-23 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuk_aktivnost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fukaktivnost',
            options={'managed': False},
        ),
    ]
