# Generated by Django 3.2.10 on 2023-03-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuk_aktivnost', '0002_alter_fukaktivnost_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fukaktivnost',
            table='fuk_aktivnost',
        ),
    ]
