# Generated by Django 3.2.10 on 2022-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FukOrganizacija',
            fields=[
                ('org_id', models.BigAutoField(db_column='ORG_ID', primary_key=True, serialize=False)),
                ('org_naziv', models.CharField(db_column='ORG_Naziv', max_length=200)),
                ('org_pnaziv', models.CharField(blank=True, db_column='ORG_Pnaziv', max_length=400, null=True)),
                ('org_adresa', models.CharField(blank=True, db_column='ORG_Adresa', max_length=200, null=True)),
                ('org_mesto', models.CharField(blank=True, db_column='ORG_Mesto', max_length=100, null=True)),
                ('org_sifmesta', models.IntegerField(blank=True, db_column='ORG_SifMesta', null=True)),
                ('org_opstina', models.CharField(blank=True, db_column='ORG_Opstina', max_length=100, null=True)),
                ('org_sifopstine', models.IntegerField(blank=True, db_column='ORG_SifOpstine', null=True)),
                ('org_brtel', models.CharField(blank=True, db_column='ORG_BrTel', max_length=100, null=True)),
                ('org_email', models.CharField(blank=True, db_column='ORG_Email', max_length=100, null=True)),
                ('org_maticnibr', models.CharField(blank=True, db_column='ORG_MaticniBr', max_length=10, null=True)),
                ('org_pib', models.CharField(blank=True, db_column='ORG_PIB', max_length=10, null=True)),
                ('org_budzet', models.IntegerField(blank=True, db_column='ORG_Budzet', null=True)),
                ('org_pob', models.IntegerField(blank=True, db_column='ORG_POB', null=True)),
                ('org_pdv', models.IntegerField(blank=True, db_column='ORG_PDV', null=True)),
                ('org_ptt', models.IntegerField(blank=True, db_column='ORG_PTT', null=True)),
                ('org_pak', models.IntegerField(blank=True, db_column='ORG_PAK', null=True)),
                ('org_sifdelatnosti', models.IntegerField(blank=True, db_column='ORG_SifDelatnosti', null=True)),
                ('org_nazivdelatnosti', models.CharField(blank=True, db_column='ORG_NazivDelatnosti', max_length=200, null=True)),
                ('rca_aktivan', models.IntegerField(blank=True, db_column='RCA_Aktivan', null=True)),
                ('rca_aktivanod', models.DateTimeField(blank=True, db_column='RCA_aktivanOD', null=True)),
                ('rca_aktivando', models.DateTimeField(blank=True, db_column='RCA_aktivanDO', null=True)),
                ('rca_brojreaktivacija', models.IntegerField(blank=True, db_column='RCA_BrojReaktivacija', null=True)),
                ('rca_sts', models.IntegerField(blank=True, db_column='RCA_STS', null=True)),
                ('rca_tmstp', models.DateTimeField(db_column='RCA_TMSTP')),
            ],
            options={
                'db_table': 'fuk_organizacija',
                'managed': False,
            },
        ),
    ]
