# Generated by Django 3.2.10 on 2022-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FukPotpis',
            fields=[
                ('ptps_id', models.BigAutoField(db_column='PTPS_ID', primary_key=True, serialize=False)),
                ('dok_id', models.BigIntegerField(blank=True, db_column='DOK_ID', null=True)),
                ('dok_tip', models.IntegerField(blank=True, db_column='DOK_Tip', null=True)),
                ('ptps_vrsta', models.IntegerField(blank=True, db_column='PTPS_Vrsta', null=True)),
                ('ptps_ime', models.CharField(blank=True, db_column='PTPS_Ime', max_length=200, null=True)),
                ('ptps_prezime', models.CharField(blank=True, db_column='PTPS_Prezime', max_length=200, null=True)),
                ('ptps_datum', models.DateField(blank=True, db_column='PTPS_Datum', null=True)),
                ('ptps_potpis', models.CharField(blank=True, db_column='PTPS_Potpis', max_length=200, null=True)),
                ('rca_aktivan', models.IntegerField(blank=True, db_column='RCA_Aktivan', null=True)),
                ('rca_aktivanod', models.DateTimeField(blank=True, db_column='RCA_aktivanOD', null=True)),
                ('rca_aktivando', models.DateTimeField(blank=True, db_column='RCA_aktivanDO', null=True)),
                ('rca_brojreaktivacija', models.IntegerField(blank=True, db_column='RCA_BrojReaktivacija', null=True)),
                ('rca_sts', models.IntegerField(blank=True, db_column='RCA_STS', null=True)),
                ('rca_tmstp', models.DateTimeField(db_column='RCA_TMSTP')),
            ],
            options={
                'db_table': 'fuk_potpis',
                'managed': False,
            },
        ),
    ]
