# Generated by Django 3.2.10 on 2022-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FukRizik',
            fields=[
                ('rsk_id', models.BigAutoField(db_column='RSK_ID', primary_key=True, serialize=False)),
                ('rsk_ciljpp', models.CharField(blank=True, db_column='RSK_CiljPP', max_length=500, null=True)),
                ('rsk_sifra', models.CharField(blank=True, db_column='RSK_Sifra', max_length=100, null=True)),
                ('rsk_naziv', models.CharField(blank=True, db_column='RSK_Naziv', max_length=2048, null=True)),
                ('rsk_verzija', models.CharField(blank=True, db_column='RSK_Verzija', max_length=200, null=True)),
                ('rsk_iverzija', models.IntegerField(blank=True, db_column='RSK_IVerzija', null=True)),
                ('rsk_zadlice', models.CharField(blank=True, db_column='RSK_ZadLice', max_length=500, null=True)),
                ('rsk_uticaj', models.IntegerField(blank=True, db_column='RSK_Uticaj', null=True)),
                ('rsk_verovatnoca', models.IntegerField(blank=True, db_column='RSK_Verovatnoca', null=True)),
                ('rsk_efekat', models.IntegerField(blank=True, db_column='RSK_Efekat', null=True)),
                ('rsk_odglice', models.CharField(blank=True, db_column='RSK_OdgLice', max_length=200, null=True)),
                ('rsk_mere', models.CharField(blank=True, db_column='RSK_Mere', max_length=500, null=True)),
                ('rsk_odgliceprac', models.CharField(blank=True, db_column='RSK_OdgLicePrac', max_length=200, null=True)),
                ('rsk_datum', models.DateField(blank=True, db_column='RSK_Datum', null=True)),
                ('rsk_datumpracenja', models.DateField(blank=True, db_column='RSK_DatumPracenja', null=True)),
                ('rsk_datumpracenja2', models.DateField(blank=True, db_column='RSK_DatumPracenja2', null=True)),
                ('rca_aktivan', models.IntegerField(blank=True, db_column='RCA_Aktivan', null=True)),
                ('rca_aktivanod', models.DateTimeField(blank=True, db_column='RCA_aktivanOD', null=True)),
                ('rca_aktivando', models.DateTimeField(blank=True, db_column='RCA_aktivanDO', null=True)),
                ('rca_brojreaktivacija', models.IntegerField(blank=True, db_column='RCA_BrojReaktivacija', null=True)),
                ('rca_sts', models.IntegerField(blank=True, db_column='RCA_STS', null=True)),
                ('rca_tmstp', models.DateTimeField(db_column='RCA_TMSTP')),
            ],
            options={
                'db_table': 'fuk_rizik',
                'managed': False,
            },
        ),
    ]
